name: build process
run-name: Build process

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}
  schedule:
    - cron: '0 0 1 */2 *'  

jobs:

  trigger-build-diskimage-almalinux9:
    runs-on: ubuntu-latest
    steps:
      - name: Start diskimage build - AlmaLinux 9
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-diskimage-almalinux9-upload.yml',
              ref: context.ref,
            });


  wait-for-build-diskimage-almalinux9:
    runs-on: ubuntu-latest
    needs: trigger-build-diskimage-almalinux9
    steps:
      - name: Wait for build-diskimages almalinux9 to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'build-diskimage-almalinux9'  # does not show (ubuntu-latest) as it runs a container
          wait-interval: 10
